#albacore parameters
FLOWCELL: "FLO-MIN106"
KIT: "SQK-RBK004"
ALBACORE_VERSION: "2.3.3" #available versions : 2.3.0 , 2.3.1 , 2.3.3
#input base directory of raw fast5 files from MiniKnow
BASEDIR: "fast5"

#Variables below should not have to be modified on a run by run basis
#script for aggregating individual albacore runs
GATHER: "scripts/gather_albacore_results.py"
